// app-mobile/components/ShareCard.tsx
import React from "react";
import { View, Text, StyleSheet, Image } from "react-native";

export type ShareCardAi = {
  score: number;
  vibe: string;
  notes: string[];
  tags: string[];
  analysisShort?: string[];
  suggestionsShort?: string[];
};

type ShareCardProps = {
  imageUri: string | null;
  fallbackImage: string;
  ai: ShareCardAi;
};

// Clamp long AI lines so they fit nicely in ~2 rows on the card
const clampForShareCard = (text: string, maxChars = 120): string => {
  if (!text) return "";
  if (text.length <= maxChars) return text;

  const shortened = text.slice(0, maxChars);
  const lastSpace = shortened.lastIndexOf(" ");

  const safeCut =
    lastSpace > 40 ? shortened.slice(0, lastSpace) : shortened;

  return safeCut.trim() + "…";
};

/**
 * Shareable 4:5 outfit card.
 *
 * Layout:
 *  - Top: photo with score pill
 *  - Middle: vibe + tags
 *  - Bottom: Aura's Analysis & Aura's Suggestions (compact bullets)
 */
export const ShareCard: React.FC<ShareCardProps> = ({
  imageUri,
  fallbackImage,
  ai,
}) => {
  const score =
    typeof ai?.score === "number" && !Number.isNaN(ai.score)
      ? ai.score
      : 7.5;

  const vibe = ai?.vibe || "Styled outfit";


  const tags: string[] = Array.isArray(ai?.tags) ? ai.tags : [];

  const rawAnalysisShort: string[] =
    Array.isArray(ai.analysisShort) && ai.analysisShort.length > 0
      ? ai.analysisShort
      : Array.isArray(ai.notes)
        ? ai.notes.slice(0, 3)
        : [];

  const rawSuggestionsShort: string[] =
    Array.isArray(ai.suggestionsShort) && ai.suggestionsShort.length > 0
      ? ai.suggestionsShort
      : Array.isArray(ai.notes)
        ? ai.notes.slice(3, 5)
        : [];

  const analysisLines = rawAnalysisShort
    .slice(0, 3)
    .map((line) => clampForShareCard(line));

  const suggestionLines = rawSuggestionsShort
    .slice(0, 2)
    .map((line) => clampForShareCard(line));

  const hasSuggestions = suggestionLines.length > 0;


  return (
    <View style={styles.card}>
      {/* PHOTO */}
      <View style={styles.imageContainer}>
        <Image
          source={{ uri: imageUri ?? fallbackImage }}
          style={styles.image}
          resizeMode="contain"
        />
        {/* <View style={styles.imageGradient} /> */}
        <View style={styles.scorePill}>
          <Text style={styles.scoreValue}>{score.toFixed(1)}</Text>
          <Text style={styles.scoreSuffix}>/10</Text>
        </View>
      </View>

      {/* CONTENT */}
      <View style={styles.body}>
        {/* vibe */}
        <View style={styles.vibeBlock}>
          <Text style={styles.vibeTitle}>Aura&apos;s vibe</Text>
          <Text style={styles.vibeText} numberOfLines={2}>
            {vibe}
          </Text>
        </View>

        {/* tags */}
        {tags.length > 0 && (
          <View style={styles.tagsRow}>
            {tags.slice(0, 4).map((tag, idx) => (
              <View key={idx} style={styles.tagPill}>
                <Text style={styles.tagText}>{tag}</Text>
              </View>
            ))}
          </View>
        )}

        {/* analysis + suggestions */}
        <View style={styles.analysisWrapper}>
          {analysisLines.length > 0 && (
            <View
              style={[
                styles.sectionBlock,
                hasSuggestions && styles.sectionBlockDivider,
              ]}
            >
              <Text style={styles.sectionTitle}>Aura&apos;s Analysis</Text>
              {analysisLines.map((line, idx) => (
                <View key={`a-${idx}`} style={styles.noteRow}>
                  <Text style={styles.bullet}>•</Text>
                  <Text style={styles.noteText} numberOfLines={2}>
                    {line}
                  </Text>
                </View>
              ))}
            </View>
          )}

          {hasSuggestions && (
            <View style={styles.sectionBlock}>
              <Text style={styles.sectionTitle}>Aura&apos;s Suggestions</Text>
              {suggestionLines.map((line, idx) => (
                <View key={`s-${idx}`} style={styles.noteRow}>
                  <Text style={styles.bullet}>•</Text>
                  <Text style={styles.noteText} numberOfLines={2}>
                    {line}
                  </Text>
                </View>
              ))}
            </View>
          )}
        </View>

        {/* footer brand */}
        <View style={styles.footerRow}>
          <View style={{ flexShrink: 1 }}>
            <Text style={styles.footerBrand}>AI Stylist · Aura</Text>
            <Text style={styles.footerSub} numberOfLines={1}>
              Style rating generated by your personal AI stylist.
            </Text>
          </View>
          <Text style={styles.footerHandle}>@yourapphandle</Text>
        </View>
      </View>
    </View>
  );
};

export default ShareCard;

const styles = StyleSheet.create({
  card: {
    width: "100%", // full width of the shell (ShareCardScreen handles maxWidth)
    aspectRatio: 2 / 3,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#020617",
  },

  // IMAGE
  imageContainer: {
    marginTop: "1%",
    flex: 0.69,
    position: "relative",
    backgroundColor: "#020617",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imageGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 0,
    backgroundColor: "rgba(15,23,42,0.9)",
  },
  scorePill: {
    position: "absolute",
    right: 14,
    bottom: 12,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34,197,94,0.95)",
    flexDirection: "row",
    alignItems: "flex-end",
  },
  scoreValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ECFDF5",
  },
  scoreSuffix: {
    fontSize: 11,
    color: "#DCFCE7",
    marginLeft: 4,
  },

  // BODY
  body: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#020617",
  },

  vibeBlock: {
    marginBottom: 4,
  },
  vibeTitle: {
    fontSize: 11,
    fontWeight: "600",
    color: "#E5E7EB",
    marginBottom: 2,
  },
  vibeText: {
    fontSize: 11,
    color: "#9CA3AF",
  },

  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
    marginBottom: 6,
  },
  tagPill: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    backgroundColor: "rgba(79,70,229,0.2)",
    marginRight: 6,
    marginBottom: 4,
  },
  tagText: {
    fontSize: 10,
    color: "#C7D2FE",
  },

  analysisWrapper: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(55,65,81,0.9)",
    backgroundColor: "rgba(15,23,42,0.98)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  sectionBlock: {
    marginBottom: 4,
  },
  sectionBlockDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(55,65,81,0.8)",
    paddingBottom: 4,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "600",
    color: "#E5E7EB",
    marginBottom: 2,
  },
  noteRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 2,
  },
  bullet: {
    fontSize: 10,
    color: "#6366F1",
    marginRight: 4,
    marginTop: 1,
  },
  noteText: {
    flex: 1,
    fontSize: 10,
    color: "#E5E7EB",
    lineHeight: 14,
  },

  footerRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  footerBrand: {
    fontSize: 11,
    fontWeight: "700",
    color: "#F9FAFB",
  },
  footerSub: {
    fontSize: 10,
    color: "#9CA3AF",
  },
  footerHandle: {
    fontSize: 10,
    color: "#6B7280",
    marginLeft: 8,
  },
});
